#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_DOMAIN_LENGTH 1000
#define MAX_LINE_LENGTH 1000
#define REGEX_PATTERN "(?:\\w+\\.)$abfut"

// literrally generated by Oracle A.k.A. OpenAI

int main(int argc, char *argv[]) {
    if (argc < 2) {
        printf("Usage: %s <input_file>\n", argv[0]);
        return 1;
    }
    printf("lets go!\n");
    char *input_file = argv[1];
    FILE *fp = fopen(input_file, "r");

    if (fp == NULL) {
        printf("Error opening file: %s\n", input_file);
        return 1;
    }

    char domain[MAX_DOMAIN_LENGTH];
    char line[MAX_LINE_LENGTH];
    char *regex_pattern = REGEX_PATTERN;
    char new_regex_pattern[MAX_LINE_LENGTH];

    while (fgets(line, MAX_LINE_LENGTH, fp) != NULL) {
        int length = strlen(line);

        // Remove newline character
        if (line[length - 1] == '\n') {
            line[length - 1] = '\0';
        }

        // Replace wildcard with domain and print regex pattern
        snprintf(domain, MAX_DOMAIN_LENGTH, "%s", line);
        char *pos = strstr(regex_pattern, "$abfut");
        int prefix_len = pos - regex_pattern;
        sprintf(new_regex_pattern, "%.*s%s%s", prefix_len, regex_pattern, domain, pos + 6);
        printf("%s\n", new_regex_pattern);
    }

    fclose(fp);
    return 0;
}
